"""add_organization_metadata_columns

Revision ID: a76ebf7376cf
Revises: 8f16b23a9d01
Create Date: 2026-08-21 15:57:55.184056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a76ebf7376cf'
down_revision: Union[str, None] = '8f16b23a9d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.add_column('data_import_jobs', sa.Column('file_blob_path', sa.String(length=500), nullable=True))
    op.add_column('data_import_jobs', sa.Column('file_blob_url', sa.Text(), nullable=True))
    op.create_index('ix_inv_tx_closing_date', 'inventory_transactions', ['closing_stock', 'date'], unique=False)
    op.create_index('ix_inv_tx_expiry_closing', 'inventory_transactions', ['expiry_date', 'closing_stock'], unique=False)
    op.create_index('ix_items_barcode_org', 'items', ['barcode', 'org_id'], unique=False)
    op.add_column('locations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_locations_is_active'), 'locations', ['is_active'], unique=False)
    op.create_index('ix_locations_org_active', 'locations', ['org_id', 'is_active'], unique=False)
    op.create_index('ix_locations_org_type', 'locations', ['org_id', 'type'], unique=False)
    op.add_column('organizations', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('gstin', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('dl_number', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('settings', sa.JSON(), nullable=True))
    op.alter_column('organizations', 'plan',
               existing_type=postgresql.ENUM('single_pharmacy', 'multi_pharmacy', name='org_plan'),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'admin', 'staff', 'vendor', name='user_role'),
               server_default=None,
               existing_nullable=False)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email_active', table_name='users')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'admin', 'staff', 'vendor', name='user_role'),
               server_default=sa.text("'staff'::user_role"),
               existing_nullable=False)
    op.alter_column('organizations', 'plan',
               existing_type=postgresql.ENUM('single_pharmacy', 'multi_pharmacy', name='org_plan'),
               server_default=sa.text("'single_pharmacy'::org_plan"),
               nullable=True)
    op.drop_column('organizations', 'settings')
    op.drop_column('organizations', 'dl_number')
    op.drop_column('organizations', 'gstin')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'address')
    op.drop_index('ix_locations_org_type', table_name='locations')
    op.drop_index('ix_locations_org_active', table_name='locations')
    op.drop_index(op.f('ix_locations_is_active'), table_name='locations')
    op.drop_column('locations', 'is_active')
    op.drop_index('ix_items_barcode_org', table_name='items')
    op.drop_index('ix_inv_tx_expiry_closing', table_name='inventory_transactions')
    op.drop_index('ix_inv_tx_closing_date', table_name='inventory_transactions')
    op.drop_column('data_import_jobs', 'file_blob_url')
    op.drop_column('data_import_jobs', 'file_blob_path')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    # ### end Alembic commands ###
